name: boxing

services:
  web:
    build: .
    container_name: web
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
