# Generated by Django 5.1.6 on 2025-03-14 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number_fight', models.PositiveIntegerField()),
                ('fighter_1', models.CharField(max_length=50)),
                ('fighter_2', models.CharField(max_length=50)),
                ('winner', models.CharField(blank=True, choices=[('fighter_1', 'Боец 1'), ('fighter_2', 'Боец 2')], max_length=10, null=True)),
            ],
            options={
                'ordering': ['room', 'number_fight'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uuid_room', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomJudges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('judge', models.CharField(max_length=100)),
                ('round_number', models.IntegerField()),
                ('red_fighter', models.CharField(max_length=100)),
                ('blue_fighter', models.CharField(max_length=100)),
                ('red_remark', models.CharField(max_length=100)),
                ('blue_remark', models.CharField(max_length=100)),
                ('winner', models.CharField(choices=[('red', 'Красный угол'), ('blue', 'Синий угол')], max_length=10)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='referee.fight')),
            ],
        ),
    ]
