# Generated by Django 5.1.6 on 2025-03-14 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fight',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='referee.room'),
        ),
        migrations.AddField(
            model_name='roomjudges',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_judges', to='referee.room'),
        ),
        migrations.AddField(
            model_name='roomjudges',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_judges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='judges',
            field=models.ManyToManyField(related_name='judges_rooms', through='referee.RoomJudges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notes',
            index=models.Index(fields=['round_number'], name='referee_not_round_n_22d9bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='notes',
            constraint=models.UniqueConstraint(fields=('fight', 'judge', 'round_number'), name='unique_fight_round'),
        ),
        migrations.AddIndex(
            model_name='fight',
            index=models.Index(fields=['room', 'number_fight'], name='referee_fig_room_id_d1ab34_idx'),
        ),
        migrations.AddIndex(
            model_name='fight',
            index=models.Index(fields=['fighter_1'], name='referee_fig_fighter_d4396b_idx'),
        ),
        migrations.AddIndex(
            model_name='fight',
            index=models.Index(fields=['fighter_2'], name='referee_fig_fighter_0da26e_idx'),
        ),
        migrations.AddConstraint(
            model_name='fight',
            constraint=models.UniqueConstraint(fields=('room', 'number_fight'), name='unique_number_fight_room'),
        ),
        migrations.AddConstraint(
            model_name='roomjudges',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_room_user'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='referee_roo_name_bd3d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['boss'], name='referee_roo_boss_id_59886c_idx'),
        ),
    ]
